config/routes.rb
Rails.application.routes.draw do

  get 'user/sign_in' => "user#sign_in"
  post 'user/logged_in' => "user#logged_in"
  post 'list/create' => "list#create"
  post 'list/destroy' => "list#destroy"
  post 'task/create' => "task#create"
  post 'task/complete' => "task#complete"
  post 'task/destroy' => "task#destroy"
  get 'profile' => "user#profile"
  get "/auth/:provider/callback" => "user#create_from_omniauth"
  get 'user/logout' => "user#logout"
  get 'list/search' => "list#search", as: 'search'
  post 'list/search' => "list#search_result"

  resources :user
  resources :list, only: [:index, :show, :update]

  root "user#index"

end

app/models/authentication.rb
    class Authentication < ActiveRecord::Base

     belongs_to :user

      def self.create_with_omniauth(auth_hash)
        create! do |auth|
          auth.provider = auth_hash["provider"]
          auth.uid = auth_hash["uid"]
          auth.token = auth_hash["credentials"]["token"]
        end
      end

      def update_token(auth_hash)
        self.token = auth_hash["credentials"]["token"]
        self.save
      end

    end

app/models/list.rb
class List < ActiveRecord::Base

	has_many :tasks
	belongs_to :user

	validates_uniqueness_of :user_id, message: "Each person can only have one list."
	
end

app/models/task.rb
class Task < ActiveRecord::Base

	belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :email, format: { with: /@/, message: "Emails must have @."}
	validates_uniqueness_of :email, message: "This email has been registered. Please use another email."
	
	has_many :lists
	has_many :authentications, :dependent => :destroy

	mount_uploader :avatar, AvatarUploader

	def self.create_with_auth_and_hash(authentication,auth_hash)
    	create! do |u|
    		u.password = Time.now.to_s
    	  u.name = auth_hash["info"]["first_name"]
    	  u.email = auth_hash["extra"]["raw_info"]["email"]
    	  u.authentications<<(authentication)
    	end
  	end

 	def fb_token
  		x = self.authentications.where(:provider => :facebook).first
  	  	return x.token unless x.nil?
  	end

  	def password_optional?
 	    true
 	 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/list_controller.rb
class ListController < ApplicationController

	def index
		if User.find(session[:user_id]).role == "Admin"
			@admin = 1
			@lists = List.all
		end
		if List.find_by(user_id: session[:user_id]).blank?
			@empty = 1
		else
			@list = List.find_by(user_id: session[:user_id])
			@tasks = @list.tasks
		end
	end

	def create
		@list = List.create(user_id: session[:user_id], title: params[:list][:title])
		flash[:success] = "You have created #{@list.title}."
		redirect_to list_index_path
	end

	def destroy
		List.destroy(params[:list_id])
	end

	def search
	end

	def search_result
		@lists = List.find_by(title: params[:title])
		render "list/search"
	end

	private

 	def list_params
    params.require(:list).permit(:title)
  	end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController

	def create
		Task.create(list_id: params[:list_id], description: params[:description] , status: 0)
		redirect_to list_index_path
	end

	def complete
		@task = Task.find(params[:task_id])
		if @task.status == false
			@task.update(status: true)
		else
			@task.update(status: false)
		end
		redirect_to list_index_path
	end

	def destroy
		@list = List.find(params[:list_id])
		@tasks = @list.tasks
		@tasks.each do |t|
			if t.status == true 
				t.destroy
			end
		end
		respond_to do |format|
			format.html { redirect_to list_index_path }
			format.js { render "list/index"}
		end

	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def index
		@user = User.new

	end

	def new

	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Your account has been created."
			session[:user_id] = @user.id
			redirect_to list_index_path
		else
			error_message = @user.errors.messages
			flash[:alert] = "#{error_message[:email].join}"
			redirect_to new_user_path
		end
	end

	def sign_in
		@user = User.new
		render "user/signin"
	end


	def logged_in
		@user = User.find_by(email: params[:user][:email]).try(:authenticate, params[:user][:password])
		if @user
			flash[:success] = "You have logged in."
			session[:user_id] = @user.id
			redirect_to list_index_path
		else
			flash[:alert] = "Invalid email/password."
			redirect_to user_sign_in_path
		end
	end

	def profile
		@user = User.find(session[:user_id])
	end

	def update
		byebug
		@user = User.find(session[:user_id])
		@user.update(avatar: params[:user][:avatar])
		redirect_to profile_path
	end

	def create_from_omniauth
        auth_hash = request.env["omniauth.auth"]

        authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
        if authentication.user
          @user = authentication.user 
          authentication.update_token(auth_hash)
        else
          @user = User.create_with_auth_and_hash(authentication,auth_hash)
        end
		flash[:success] = "Your account has been created."
		session[:user_id] = @user.id
		redirect_to list_index_path
     end

     def logout
		reset_session
		redirect_to user_index_path
     end

	private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(level)
    	case level.to_sym
     	 when :success then "alert alert-success"
     	 when :info then "alert alert-info"
     	 when :danger then "alert alert-danger"
     	 when :warning then "alert alert-warning"
   		end
 	 end

end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalToDoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
    <div class="text-center <%= flash_class(key) %>">
      <%= value %>
    </div>
<% end %>
<% if session[:user_id] %>
<%= link_to "Profile", profile_path %>&nbsp <%= link_to "To Do List", list_index_path %>&nbsp <%= link_to "Logout", user_logout_path %>
<% end %>
<br>
<br>
<br>
<%= yield %>

</body>
</html>

app/views/list/destroy.js.erb
	$('.destroy').bind('ajax:success', function(){
		alert("test");
		$('#clear_btn').remove();
	})

app/views/list/index.html.erb
<% if @admin %>
	<%= link_to "Filter", search_path %>
	<br>
	<br>
	<table>
	<% @lists.each do |l| %>
			<td>
				<tr>
					<%= l.title %>
				</tr>
					<% l.tasks.each do |t| %>
						<tr>
						<% if t.status == false %>
							<%= "[ ]" + "#{t.description}" %>
						<% else %>
							<%= "[X]" + "#{t.description}" %>
						<% end %>
						</tr>
					<% end %>
			</td>
	<% end %>
	</table>
<% else %>
	<% if @empty %>
	<p> You do not have any To Do List.<br>Please create one.<br></p>
		<form action="/list/create" method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
			<label for="title">Title</label><br>
			<input type="text" name="list[title]"><br>
			<input type="submit" value="Create To Do List">
		</form>
	<% end %>

	<% if @list %>
	<h3><%= @list.title %></h3>
	<table>
	<% @tasks.each do |t| %>
		<tr>
		<td><% if t.status == false %>
			<%= "[ ]" %>
		</td>
		<td><%= t.description %></td>
		<td>
		<form action="/task/complete" method="post" >
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
			<input type="hidden" name="task_id" value="<%= t.id%>">
			<input type="submit" value="Status update">
		</form>
		</tr>
		<% end %>
	<% end %>
	</table>
	<br>
	<br>
	<table>
		<% @tasks.each do |t| %>
		<tr>
			<% if t.status == true %>
			<td>
			<p class="completed"><%= "[X]"+ t.description %></p>
			</td>
			<td>
			<form action="/task/complete" method="post" class="completed">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
				<input type="hidden" name="task_id" value="<%= t.id%>">
				<input type="submit" value="Status update">
			</form>
			</tr>
			</td>
			<% end %>
		<% end %>
	</table>



	<br><br><br>
	<form action="/task/create" method="post" >
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
		<input type="hidden" name="list_id" value="<%= @list.id%>">
		<label for="description">Add new task</label><br>
		<input type="text" name="description"><br>
		<input type="submit" value="Add task to list">
	</form>
	<br>
	<form action="/list/destroy" method="post" >
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
		<input type="hidden" name="list_id" value="<%= @list.id%>">
		<input type="submit" value="Delete the list">
	</form>
		<br>
	<form action="/task/destroy" method="post" data-remote="true" class="destroy">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
		<input type="hidden" name="list_id" value="<%= @list.id%>">
		<input type="submit" value="Clear completed tasks" id="clear_btn">
	</form>

<% end %>
<% end %>

app/views/list/index.js.erb
	$('.destroy').bind('ajax:success', function(){
		alert("You are removing all completed tasks.");
		$('.completed').remove();
	})

app/views/list/search.html.erb
<form action="/list/search" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
	<label for="title">Title</label><br>
	<input type="text" name="title"><br>
	<input type="submit" value="Search for To Do List">
</form>

<br><br>

<% if @lists %>
		<p> Search Results </p><br>
		<h3><%= @lists.title %></h3>
		<table>
			<% @lists.tasks.each do |t| %>
			<tr>
				<td><% if t.status == false %>
				<%= "[ ]" %>
				</td>
				<td><%= t.description %></td>
				</tr>
				<% end %>
			<% end %>
		</table>
<% end %>

app/views/user/index.html.erb
Welcome to To-Do-List
<br>
<br>

Please select option to continue. <br>
<%= link_to "Sign In", user_sign_in_path %>
<%= link_to "Register", new_user_path %>
<%= link_to t(".sign_in_with_Facebook"), "/auth/facebook" %>

app/views/user/new.html.erb
Please fill in the form below to register.
<br>
<br>


<form action="/user" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
	<label for="name">Name</label><br>
	<input type="text" name="user[name]">
	<br>
	<label for="email">Email</label><br>
	<input type="text" name="user[email]">
	<br>
	<label for="password">Password</label><br>
	<input type="password" name="user[password]">
	<br>
	<input type="submit" value="Register">
</form>

app/views/user/profile.html.erb
<% if @user.avatar.file.nil? %>
	<%= image_tag("avatar_placeholder.png", size: '250x250') %>
<% else %>
    <%= image_tag(@user.avatar.url.to_s, alt: "#{@user.email}'s Avatar", size: '250x250') %><br>
<% end %>
<br>

<%= form_for @user do |f| %>
    <%= f.file_field :avatar %>
    <%= f.submit "Upload" %>
<% end %>

<br>
Name : <%= @user.name %><br>
Email : <%= @user.email %><br>
Access : <%= @user.role %><br>

app/views/user/signin.html.erb
Please enter your credentials below to sign in.
<br>
<br>


<form action="/user/logged_in" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
	<label for="email">Email</label><br>
	<input type="text" name="user[email]">
	<br>
	<label for="password">Password</label><br>
	<input type="password" name="user[password]">
	<br>
	<input type="submit" value="Sign In">
</form>